# This is for the development environment.
# Use your own customized configuration for the production environment.

services:
  rabbitmq:
    image: rabbitmq:3.10.7-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: freestuff-dev
      RABBITMQ_DEFAULT_PASS: freestuff-dev

  redis:
    image: redis:7.0.5-alpine
    ports:
      - 6379:6379

  mongodb:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: freestuff-dev
      MONGO_INITDB_ROOT_PASSWORD: freestuff-dev
      MONGO_INITDB_DATABASE: freestuffbot

volumes:
  dbdata:
