

export default class Tracking {

  public static readonly DISCORD_POINTS = {
    PAGE_DISCOVERED_SETTINGS_MAIN: 1 << 0,
    PAGE_DISCOVERED_SETTINGS_CHANGE_CHANNEL: 1 << 1,
    PAGE_DISCOVERED_SETTINGS_CHANGE_LANGUAGE: 1 << 2,
    PAGE_DISCOVERED_SETTINGS_CHANGE_ROLE: 1 << 3,
    PAGE_DISCOVERED_SETTINGS_CHANGE_DISPLAY: 1 << 4,
    PAGE_DISCOVERED_SETTINGS_CHANGE_FILTER: 1 << 5,
    PAGE_DISCOVERED_SETTINGS_CHANGE_MORE: 1 << 6,
    PAGE_DISCOVERED_FREE_GAMES_LIST: 1 << 7,
    ACTION_DATA_REQUESTED: 1 << 8,
    ACTION_BETA_ENABLED_PREVIOUSLY: 1 << 9,
    ACTION_TEST_TRIGGERED: 1 << 10,
    ACTION_RESEND_TRIGGERED: 1 << 11,
    ACTION_MYSTERIOUS_BUTTON_CLICKED: 1 << 12,
    NEWS_FEED_SLOT_A: 1 << 24,
    NEWS_FEED_SLOT_B: 1 << 25,
    NEWS_FEED_SLOT_C: 1 << 26,
    NEWS_FEED_SLOT_D: 1 << 27,
    NEWS_FEED_SLOT_E: 1 << 28,
    NEWS_FEED_SLOT_F: 1 << 29,
    NEWS_FEED_SLOT_G: 1 << 30
  }

}
