version: "3.3"

services:
  bot:
    image: ghcr.io/freestuffbot/discord:master
    environment:
      NODE_ENV: "production" # don't change
      FSB_DBOT_TOKEN: "your bot token here"
      FSB_DBOT_ID: "your bot id here like 756183898156957850"
      FSB_MONGO_URL: "mongodb://host.docker.internal:27017/admin"
      FSB_FSAPI_KEY: "your freestuff api key here"
      FSB_FSAPI_TYPE: "basic" # don't change

    # SINGLE SHARD
      FSB_MODE: "single"
    # or MULTIPLE SHARDS
      FSB_MODE: "shard"
      FSB_SHARD_IDS: "1,2,3,4"
      FSB_SHARD_COUNT: "4"
    # or DYNAMIC SHARDS BY WORKING FOR A MANAGER
      FSB_MODE: "worker"
      FSB_WORKER_HOST: "ws://manager.localhost"

    # Below is optional but if you would like to have real-time events you need to start the webhook server
      FSB_SERVER_ENABLE: "true"
      FSB_SERVER_PORT: "6622"
      FSB_WEBHOOK_SECRET: "your custom webhook secret"
      FSB_WEBHOOK_ENDPOINT: "/webhooks/freestuff"

    # If you like to have prometheus metrics enabled use the following config. You can have both the webhook server and metrics, just delete duplicate environment variables
      FSB_SERVER_ENABLE: "true"
      FSB_SERVER_PORT: "6622"
      FSB_METRICS_ENDPOINT: "/metrics"

  # Only if using the webhook server
    ports:
      - 6622:6622

  # Also optional but recommended
    restart_policy:
      condition: any
      delay: 5s
      max_attempts: 3
      window: 30s
