

export const MAGICNUMBER_BAD_GATEWAY = 0xFF00_01
export const MAGICNUMBER_MISSING_PERMISSIONS = 0xFF00_02
export const MAGICNUMBER_MAX_WEBHOOKS_REACHED = 0xFF00_03

export type MagicNumber
  = typeof MAGICNUMBER_BAD_GATEWAY
  | typeof MAGICNUMBER_MISSING_PERMISSIONS
  | typeof MAGICNUMBER_MAX_WEBHOOKS_REACHED
